#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

xrandr -s 1920x1080
lxpolkit &
audacious &
sxhkd &
parcellite &
#################################################
#~/.config/polybar-bspwm/launch.sh &
#~/.config/polybar/panel.sh &
tint2 -c ~/.config/tint2/dracula.tint2rc &
conky -c ~/.config/conky/sysinfo_mbcolor.conkyrc &
#picom &
#################################################

#feh --bg-fill ~/Pictures/wallpapers/xfce-leaves.svg &
lxappearance &

bspc config border_width         2
bspc config window_gap          12

#Follow mouse pointer
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Make new window on LHS instead of right
bspc config initial_polarity	first_child

#Focus on active window is now blue
bspc config focused_border_color "#3399ff"

bspc config automatic_scheme	spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
